#!/bin/bash

declare -A datasets
datasets[1]='ames_housing'
datasets[2]='bike'
datasets[3]='cal_housing'
datasets[4]='communities'
datasets[5]='concrete'
datasets[6]='energy'
datasets[7]='fb'
datasets[8]='kin8nm'
datasets[9]='life'
datasets[10]='meps'
datasets[11]='msd'
datasets[12]='naval'
datasets[13]='obesity'
datasets[14]='online_news'
datasets[15]='power'
datasets[16]='protein'
datasets[17]='star'
datasets[18]='superconductor'
datasets[19]='synth_regression'
datasets[20]='wave'
datasets[21]='wine'
datasets[22]='yacht'

datasets[100]='heart'
